//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exoft.Gamification.Api.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exoft.Gamification.Api.Services.Resources.HtmlPages", typeof(HtmlPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Reset password&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .container {
        ///            width:300px;
        ///            height:170px;
        ///            position: absolute;
        ///            padding: 20px;
        ///            background-color: #3A3E46;
        ///        }
        ///        a {
        ///            padding: 15px 30px;
        ///            border-radius: 5px;
        ///            background-color: white;
        ///            color: #3A3E46;
        ///            text-decoration: none;
        ///        }
        ///        h3, p {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgotPasswordPage {
            get {
                return ResourceManager.GetString("ForgotPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Exoft Support&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .container {
        ///            width: 300px;
        ///            height: 170px;
        ///            position: absolute;
        ///            padding: 20px;
        ///            background-color: #3A3E46;
        ///        }
        ///
        ///        h3, p {
        ///            text-align: center;
        ///            color: white;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;h3&gt;Hello {FirstName}!&lt;/h3&gt;
        ///        &lt;p&gt;You are registe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegisterPage {
            get {
                return ResourceManager.GetString("RegisterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Request achievement&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .container {
        ///            width: 300px;
        ///            height: 170px;
        ///            position: absolute;
        ///            padding: 20px;
        ///            background-color: #3A3E46;
        ///        }
        ///
        ///        h3, p {
        ///            text-align: center;
        ///            color: white;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;h3&gt;Hello!&lt;/h3&gt;
        ///        &lt;p&gt;User {userLastName} { [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RequestAchievementPage {
            get {
                return ResourceManager.GetString("RequestAchievementPage", resourceCulture);
            }
        }
    }
}
