//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exoft.Gamification.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exoft.Gamification.Api.Resources.ValidatorMessages", typeof(ValidatorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not be empty.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This uri is invalid.
        /// </summary>
        public static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains digit.
        /// </summary>
        public static string PasswordDigit {
            get {
                return ResourceManager.GetString("PasswordDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains lower case letter.
        /// </summary>
        public static string PasswordLowerCaseLetter {
            get {
                return ResourceManager.GetString("PasswordLowerCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains upper case letter.
        /// </summary>
        public static string PasswordUpperCaseLetter {
            get {
                return ResourceManager.GetString("PasswordUpperCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than or equal to {ComparisonValue}.
        /// </summary>
        public static string SmallValue {
            get {
                return ResourceManager.GetString("SmallValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {PropertyName} must be {MaxLength} chars or fewer.
        /// </summary>
        public static string TooLong {
            get {
                return ResourceManager.GetString("TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {PropertyName} must be {MinLength} chars or more.
        /// </summary>
        public static string TooShort {
            get {
                return ResourceManager.GetString("TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not a unique email address.
        /// </summary>
        public static string UniqueEmail {
            get {
                return ResourceManager.GetString("UniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not a unique name.
        /// </summary>
        public static string UniqueName {
            get {
                return ResourceManager.GetString("UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not a unique userName.
        /// </summary>
        public static string UniqueUserName {
            get {
                return ResourceManager.GetString("UniqueUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current secretString expired or not found.
        /// </summary>
        public static string UnknownSecretString {
            get {
                return ResourceManager.GetString("UnknownSecretString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not a valid email address.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not a valid role.
        /// </summary>
        public static string WrongRole {
            get {
                return ResourceManager.GetString("WrongRole", resourceCulture);
            }
        }
    }
}
